CREATE TABLE category
(
    ID      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME    VARCHAR(120) not null,
    USER_ID BIGINT       not null,

    CONSTRAINT fk_user_category
        FOREIGN KEY (USER_ID)
            REFERENCES users (id)
);

CREATE UNIQUE INDEX uk_category_user_name
    ON category (USER_ID, LOWER(NAME));